# Generated by Django 6.0.6 on 2026-07-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('session_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['last_seen'], name='analytics_h_last_se_cd8188_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=200)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('device_type', models.CharField(blank=True, default='', max_length=10)),
                ('timezone', models.CharField(blank=True, default='', max_length=60)),
                ('language', models.CharField(blank=True, default='', max_length=30)),
                ('os', models.CharField(blank=True, default='', max_length=20)),
                ('browser', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=60)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('is_returning', models.BooleanField(default=False)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['visited_at'], name='analytics_p_visited_10fd53_idx')],
            },
        ),
    ]
